import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display:'swap'
});

export const metadata: Metadata = {
  title: "Learn Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${roboto.variable} antialiased`}
    >
        <h1 className="text-center text-2xl">Comman Layout</h1>
        {children}
      </body>
    </html>
  );
}
